<H1>Lista de pessoas</H1>

<a href="<?=  $this->url('pessoa',['action' => 'adicionar'])?>" class="btn btn-success" style="margin-bottom: 10px;">Adicionar</a>

<table class="table table-stripped">
    <th>Código</th>
    <th>Nome</th>
<?php
foreach ($pessoas as $pes) :
?>
    <tr>
        <td><?= $pes->getId() ?></td>
        <td><?= $pes->getNome() ?></td>
        <td>
            <a href="<?= $this->url('pessoa', ['action'=>'editar', 'id'=>$pes->getId()]) ?>" class="btn btn-info"> <i class="glyphicon glyphicon-edit" ></i>Editar </a>
        </td>
    </tr>
<?php
endforeach;
?>
</table>